In [2]:

#input adjacency matrix
import numpy as np
d = 0.9 #damping factor
adj = np.array([[0,1/2,1/2,0,0,0],[0,0,0,0,0,0],[1/3,1/3,0,0,1/3,0],[0,0,0,0,1/2,1/2],[0,0,0,1/2,0,1/2],[0,0,0,1,0,0]])
print(adj)

[[0.         0.5        0.5        0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]]


In [3]:
#handling the node with no out going links
n=len(adj)
for i in range(n):
    if any(adj[i])==0:
        for l in range(n):
            adj[i][l]=1/n
print(adj)

[[0.         0.5        0.5        0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]]


In [4]:
#stochastic matrix formation
E = np.ones((n,n))
sto=(1-d)*E/n+d*np.transpose(adj)
print(sto)

[[0.01666667 0.16666667 0.31666667 0.01666667 0.01666667 0.01666667]
 [0.46666667 0.16666667 0.31666667 0.01666667 0.01666667 0.01666667]
 [0.46666667 0.16666667 0.01666667 0.01666667 0.01666667 0.01666667]
 [0.01666667 0.16666667 0.01666667 0.01666667 0.46666667 0.91666667]
 [0.01666667 0.16666667 0.31666667 0.46666667 0.01666667 0.01666667]
 [0.01666667 0.16666667 0.01666667 0.46666667 0.46666667 0.01666667]]


In [5]:

#Page rank of all the six nodes after each iteration
P=[]
P.append(np.ones((n,1))/n)
k=0
e=0.05
c=1
while c:
    P.append((1-d)*np.ones((n,1))+d*np.transpose(adj).dot(P[k]))
    a=abs((P[k+1]-P[k]))<e
    stop = a.all()
    if stop:
        c=0

    k=k+1

In [7]:
#Total number iteration count until stopping criteria.
for i in range(len(P)):
    print('----------------*********************----------------')
    print(f'Iteration {i}')
    
    print(P[i])
    print('--------------*********************------------------')

----------------*********************----------------
Iteration 0
[[0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]]
--------------*********************------------------
----------------*********************----------------
Iteration 1
[[0.175]
 [0.25 ]
 [0.2  ]
 [0.35 ]
 [0.25 ]
 [0.275]]
--------------*********************------------------
----------------*********************----------------
Iteration 2
[[0.1975 ]
 [0.27625]
 [0.21625]
 [0.4975 ]
 [0.355  ]
 [0.4075 ]]
--------------*********************------------------
----------------*********************----------------
Iteration 3
[[0.2063125]
 [0.2951875]
 [0.2303125]
 [0.6679375]
 [0.4301875]
 [0.5250625]]
--------------*********************------------------
----------------*********************----------------
Iteration 4
[[0.21337187]
 [0.3062125 ]
 [0.23711875]
 [0.81041875]
 [0.51394375]
 [0.63843437]]
--------------*********************------------------
----------------*************